# Generated by Django 3.1.7 on 2021-03-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_desc', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
